version: 2.1

orbs:
  docker: circleci/docker@2.4.0

workflows:
  build-test-and-deploy:
    jobs:
      - docker/publish:
          name: Publish app
          image: felixshift/release_app
          path: docker/app/
      - docker/publish:
          name: Publish db
          image: felixshift/release_db
          path: docker/db/