version: 2.1

orbs:
  docker: circleci/docker@2.4.0

workflows:
  build-test-and-deploy:
    jobs:
      - docker/publish:
          name: Publish app
          image: felixshift/release_app
          path: docker/app/
          tag: $CIRCLE_SHA1, latest
      - docker/publish:
          name: Publish db
          image: felixshift/release_db
          path: docker/db/
          tag: $CIRCLE_SHA1, latest